# Generated by Django 5.0 on 2023-12-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
    ]
